SET ECHO ON  
DROP TABLE Weapon CASCADE CONSTRAINTS;
DROP TABLE WeaponType CASCADE CONSTRAINTS;
DROP TABLE Enchantment CASCADE CONSTRAINTS;
DROP TABLE Character CASCADE CONSTRAINTS;
DROP TABLE Quests CASCADE CONSTRAINTS;
DROP TABLE Monster CASCADE CONSTRAINTS;
DROP TABLE Locations CASCADE CONSTRAINTS;
DROP TABLE DamageMulti CASCADE CONSTRAINTS;
DROP TABLE CharacterSkills CASCADE CONSTRAINTS;
DROP TABLE CharacterMagic CASCADE CONSTRAINTS;
DROP TABLE CharacterStats CASCADE CONSTRAINTS;
DROP TABLE CharacterFaction CASCADE CONSTRAINTS;
DROP TABLE QuestStarted CASCADE CONSTRAINTS;
DROP TABLE QuestLocated CASCADE CONSTRAINTS;
SET ECHO OFF
